import type { WorkCard } from "./types";

const workData: WorkCard[] = [
  {
    slug: "cb-animation-challenge",
    title: "CB Animation Challenge",
    type: "Creative Development",
    summary: "A campaign experience for a Candy Banner animation contest. Users spin an interactive slot machine to discover entries by category, then explore work submitted by developers showcasing inventive animation techniques.",
    tools: ["Vue 3", "GSAP", "Bootstrap", "Pinia", "Axios", "Express", "MongoDB"],
    link: "",
  },
  {
    slug: "batiste",
    title: "Batiste",
    type: "Creative Development",
    summary: "An interactive Batiste product experience that guides users through a hair-type quiz and recommends a matching product, creating a direct path from discovery to the product page.",
    tools: ["Nuxt 2", "GSAP", "Bootstrap", "Vuex", "Axios"],
    link: "https://www.mybatiste.ca/",
  },  
  {
    slug: "candy-digital",
    title: "Candy Digital",
    type: "Creative Web Development",
    summary: "A company website revamp created during the transition from Candy Banners to Candy Digital. The experience presents the studio's work and services through a polished, motion-led interface.",
    tools: ["Nuxt 3", "GSAP", "Bootstrap", "Matter.js", "Pinia", "Headless CMS", "Wordpress"],
    link: "https://candydigital.co/",
  },
  {
    slug: "cashmere",
    title: "Cashmere",
    type: "Creative Web Development",
    summary: "A nationwide Cashmere dress competition experience that gives the audience a way to browse and vote for standout entries while celebrating creative talent across the country.",
    tools: ["Vue 3", "GSAP", "Vuex", "Bootstrap", "Axios", "Express", "MongoDB"],
    link: "",
  },
  {
    slug: "enthuse",
    title: "Enthuse",
    type: "Creative Development",
    summary: "A festive Enthuse microsite designed to engage visitors through seasonal interactions, product discovery and downloadable discount coupons for the holiday campaign.",
    tools: ["Vue 3", "GSAP", "Bootstrap"],
    link: "",
  },
  {
    slug: "candy-digital-holiday",
    title: "Candy Digital Holiday",
    type: "Creative Development",
    summary: "A holiday microsite for Candy Digital where users create personalized GIFs, download their finished creations and share them with friends and family.",
    tools: ["Vue 3", "GSAP", "Bootstrap"],
    link: "",
  },
  {
    slug: "klick-bayer",
    title: "Klick Bayer",
    type: "Web Development",
    summary: "A focused pitch-site concept for Klick Bayer, translating the campaign direction into a concise digital presentation with a clear visual narrative.",
    tools: ["Wordpress"],
    link: "",
  },
  {
    slug: "lallemand-biofuels",
    title: "Lallemand Biofuels",
    type: "Rich Media & Banner Development",
    summary: "A rich-media advertising experience for Lallemand Biofuels, built to communicate brand information clearly and attract attention on a large-format display.",
    tools: ["Javascript", "GSAP"],
    link: "",
  },
  {
    slug: "moreys",
    title: "Moreys",
    type: "Web Development",
    summary: "A custom Moreys food experience combining seafood products, recipes, coupons and store discovery in one WordPress site built with reusable Gutenberg blocks.",
    tools: ["Wordpress", "React"],
    link: "",
  },
  {
    slug: "cb-spring-challenge",
    title: "CB Spring Challenge",
    type: "Creative Web Development",
    summary: "A spring-break animation contest experience hosted by Candy Banner, giving developers a platform to submit creative work and visitors a way to discover and celebrate the entries.",
    tools: ["Nuxt 3", "Bootstrap", "GSAP"],
    link: "",
  },
  {
    slug: "infinite-verse",
    title: "Flyrank AI-Internship",
    type: "AI-Augmented Web Development",
    summary: "This is a Bible Web App that provides users with an immersive and interactive way to explore biblical verses and related content. An AI-augmented web experience for Infinite Verse, leveraging advanced algorithms to enhance user interaction and content personalization.",
    tools: ["Next.js", "Tailwind CSS", "GSAP", "AI tools", "Firebase", "Rest APIs"],
    link: "https://infinite-verse.vercel.app/",
  },
  {
    slug: "alpeville-c",
    title: "Alpeville C",
    type: "AI-Augmented Web Development",
    summary: "A portfolio project for Alpeville, showcasing his work, experience, and tech stack through an interactive web experience, featuring a 3D AI assistant that helps users explore and learn more about his professional background.",
    tools: ["Next.js", "Tailwind CSS", "GSAP", "React Three Fibre", "Three.js", "Meshy AI", "AI tools", "OpenAI Api", "PostgreSQL", "Strapi"],
    link: "https://alpeville-c.vercel.app/",
  },
];

export default workData;
